### ISSUE TITLE
"Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone"

### ISSUE THREAD

**Issue by ChipFraeser** [cloud-atlas-ai/obsidian-ics#103]
I'm sorry if there is an obvious fix to this error message, but I've been trying for a while and can't get the plugin to work. After executing the command in a daily note, this is the error message I can see in the Obsidian console. I am trying to pull events from 3 Google and 1 Outlook calendars.

Maybe some other noteworthy things are that my daily notes are in DD.MM.YYYY format and I execute the following line of code in the JavaScript Init plugin: "moment.locale("de")".

**Comment by muness** [comment]
Hi @ChipFraeser , are there any other symptoms? Do the events come through?

Can you test with https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.1test ? Specifically replace `main.js` in `<vault>/.obsidian/plugins/ics` with the one from this release, restart obsidian and give it a try. 🙏

**Comment by ChipFraeser** [comment]
Hello @muness,

regrettably, I still cannot pull events from the calendars, but the error message is gone. I created a new vault, tried it there, too, and it seems to work as intended there. I assume the problem is related to my settings in Obsidian.

**Comment by ChipFraeser** [comment]
I tried setting everything up from scratch again and got all 4 calendars working. Eventhough from what I tested so far everything is working properly, I can still see the same error message in the console(x150). The culrpit seems to be the outlook calendar from work. This is on the plugin version available within obsidian.

**Comment by brimwats** [comment]
![image](https://github.com/cloud-atlas-ai/obsidian-ics/assets/73113656/78164ca6-b2af-4a8e-993c-45884bd75f32)

I am also getting 10k of these errors. I haven't tried the beta yet but will tomorrow

**Comment by muness** [comment]
Closed by #104
