### ISSUE TITLE
Bug in template for ICS events in Reminder format

### ISSUE THREAD

**Issue by stoweboyd** [cloud-atlas-ai/obsidian-ics#105]
I want to have the ICS events formatted in reminder format for tasks, but there is a bug in ICS. I want the data to be encoded like this:

`(@[[yyyy-MM-DD]] hh:mm) task text`

But adding the `]]` screws up the format replacement. See in the screenshot the `yyyy-MM-DD`.

![Screenshot 2024-01-14 at 10 17 40 AM](https://github.com/cloud-atlas-ai/obsidian-ics/assets/3037422/7b73e1c2-6556-43d5-acdc-4da91b5f45b4)

Here's how it resolves when I take out the brackets:

![Screenshot 2024-01-14 at 10 17 51 AM](https://github.com/cloud-atlas-ai/obsidian-ics/assets/3037422/bf4dc02e-8681-431c-811f-fcc9cb4d5b16)

**Comment by muness** [comment]
Hi @stoweboyd , that field is only meant for the time format. It's failing because we've got superfluous content in there that the `moment` library formatting is getting tripped by, as expected.

For more complicated templates, I suggest using Templater as other users [have](https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74).

For example:

```
<%*
var events = await app.plugins.getPlugin('ics').getEvents(moment(tp.file.title,'YYYY-MM-DD'));
events.sort((a,b) => a.utime - b.utime).forEach((e) => {
    const calendar = e.icsName.replace(" ","-");
    const callUrl = e.callUrl ? ` [${e.callType}](${e.callUrl})` : '';
    const location = e.location ? ` 📍 *(${e.location})*` : '';
    const eventDate = moment.unix(e.utime).format('yyyy-MM-DD'); // Convert utime to the date format desired
    const eventTime = moment.unix(e.utime).format('HH:mm'); // Convert utime to the time format desired
    tR += `- [ ] (@[[${eventDate]]]] ${eventTime}) **${e.summary}**${location}${callUrl} #${calendar}\n`; // Format as per user request
    if (e.description) {
        const inlineDescription = e.description.replace(/(?:\r\n|\r|\n)/g," ").replace(/\s{2,}/g," ");
        tR += `    - ${inlineDescription}\n`;
    }
})
%>
```
