### ISSUE TITLE
Failure when not using daily notes

### ISSUE THREAD

**Issue by brimwats** [cloud-atlas-ai/obsidian-ics#106]
I use weekly notes, and so I tried to modify the djvs block:

```dataviewjs
var events = await app.plugins.getPlugin('ics').getEvents("{{date:2024-01-24}}");
var mdArray = [];
events.forEach((e) => {
  mdArray.push(`${e.time} ${e.summary} ${e.location}: ${e.description}`.trim())
})
dv.list(dv.array(mdArray))
```

but it errors out like so:

![image](https://github.com/cloud-atlas-ai/obsidian-ics/assets/73113656/09d09ed9-d148-4493-a35f-81d72bd6a5bf)

Before this i tried "import events" and got an error here:

```
ync onload() {
            await this.loadSettings(),
            this.addSettingTab(new WM(this.app,this)),
            this.addCommand({
                id: "import_events",
                name: "import events",
                editorCallback: async(z,b)=>{
                    let O = (0,
                    qe.getDateFromFile)(b.file, "day").format("YYYY-MM-DD");
                    var e = await this.getEvents(O);
                    let A = e.sort((t,d)=>t.utime - d.utime).map(this.formatEvent, this);
                    z.replaceRange(A.join(`
`), z.getCursor())
                }
```

**Comment by brimwats** [comment]
ahh a slight edit seems to get it somewhat there?

![image](https://github.com/cloud-atlas-ai/obsidian-ics/assets/73113656/ac9d5d4a-524f-4fac-8497-beac1efdbf05)

Here's what did work slightly:

```dataviewjs
var events = await app.plugins.getPlugin('ics').getEvents("2024-01-24");
var mdArray = [];
events.forEach((e) => {
  mdArray.push(`${e.time} ${e.summary} ${e.location}: ${e.description}`.trim())
})
dv.list(dv.array(mdArray))
```

**Comment by muness** [comment]
Hi, yep, the date format was wrong. The remaining issues you're seeing (null and undefined) are because of the formatting code. See https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74 for more examples of formatting to address those.
