### ISSUE TITLE
Error filtering events for calendar xxx: Error: Invalid date passed in to RRule.between

### ISSUE THREAD

**Issue by pm64** [cloud-atlas-ai/obsidian-ics#108]
In setting up a fresh install of this plugin that I'm very excited to use, I seem to have hit a roadblock.

I entered my Google secret URL exactly as indicated in the instructions.

But trying the example from README:

```dataviewjs
var events = await app.plugins.getPlugin('ics').getEvents("{{date:2024-02-02}}");
var mdArray = [];
events.forEach((e) => {
  mdArray.push(`${e.time} ${e.summary} ${e.location}: ${e.description}`.trim())
})
dv.list(dv.array(mdArray))
```

Renders no output on the page, and the following in console:

![image](https://github.com/cloud-atlas-ai/obsidian-ics/assets/10715458/77e5a4d4-feca-46c0-95a9-ebf9ea8bf2d4)

I reviewed the setup instructions several times, is it possible I missed something?

Any guidance would be greatly appreciated.

**Comment by muness** [comment]
Hi, my apologies, I had a typo in the README. The syntax should just be the date itself.

```
var events = await app.plugins.getPlugin('ics').getEvents("2024-02-02");
```

Please test with the command and only after that works then customize with Data view.

**Comment by pm64** [comment]
Thanks @muness, that did resolve the issue!

However, I think there's still a problem with the README's Dataview example:

```
```dataviewjs
var events = await app.plugins.getPlugin('ics').getEvents("YYYY-MM-DD");
var mdArray = [];
events.forEach((e) => {
  mdArray.push(`${e.time} ${e.summary} ${e.location}: ${e.description}`.trim())
})
dv.list(dv.array(mdArray))```
```

The README states "if you use the core Templates plugin you can add [the code above] to add events to your daily note template".

But in this case wouldn't "YYYY-MM-DD" need to be replaced with an actual date?

I know in Templater allows you to resolve the date like this:

```
moment(tp.file.title,app['internalPlugins']['plugins']['daily-notes']['instance']['options']['format'].split('/').pop()).format("YYYY-MM-DD")
```

But my use case necessitates Dataview, because it's common for events to get updated throughout the day, so the output must be dynamic.

Can the example in the README be updated to use the date of the daily note in which the Dataview query resides?

**Comment by muness** [comment]
> However, I think there's still a problem with the README's Dataview example:

Thanks for calling that out, @pm64 

[71f2dcef3875e255ddfa87edd53478c71a825de4](https://github.com/cloud-atlas-ai/obsidian-ics/commit/71f2dcef3875e255ddfa87edd53478c71a825de4) look ok?

**Comment by pm64** [comment]
It does, except I just realized the `.toFormat("yyyy-MM-dd")` bit isn't necessary. So it can be simplified:

```
var events = await app.plugins.getPlugin('ics').getEvents(dv.current().file.day);
```

**Comment by muness** [comment]
Thanks, updated!
