### ISSUE TITLE
bug: recurring all-day events aren't added

### ISSUE THREAD

**Issue by Cateroo** [cloud-atlas-ai/obsidian-ics#112]
Thanks for the great plugin, I just wanted to report a bug that I seem to be facing with use: 

All-day events that are recurring (I tested with recurring annually on date) do not show up on the calendar events list. 
Timed recurring events are fine, and all-day events are fine, but somehow when those two are combined they fail to get listed by the plugin.

This basically means I'm not getting birthday reminders, which is less than optimal 😅

**Comment by muness** [comment]
Hi Cateroo, do you have any other details? I get All Day events (from my Google calendar feeds) fine, though sometimes timezones are offset.

Also, can you double check the day before and after to make sure the events don't show up there instead?

**Comment by Cateroo** [comment]
Hi Muness,

I have checked the previous and next days. The events aren't there either.

What details would you like? I've tried different calendars (home calendar and other side calendars) but nothing works.

Just to be clear, all day events work fine, it's only when they're recurring all-day events that they don't show up. (recurring timed events are also fine)

-C

**Comment by Cateroo** [comment]
To update, I tried a bunch of trouble shooting with help from people on the obsidian discord, but no change. 
This is the code I'm using - 

`
<%*
var events = await app.plugins.getPlugin('ics').getEvents(moment(tp.file.title,"DD MMM YYYY"));
console.table(events);
events.sort((a,b) => a.utime - b.utime).forEach((e) => {
    const calendar = e.icsName.replace(" ","-");
    const callUrl = e.callUrl? ` [${e.callType}](${e.callUrl})` : '';
    const location = e.location? ` 📍*(${e.location})*` : '';
    tR+=`- [ ] #${calendar}:: ${e.time}-${e.endTime} : \`${e.summary} ${calendar}\`${location}${callUrl}\n`
})
%>
`

it seems to work for others using similar/same code, but it doesn't work for me

**Comment by Cateroo** [comment]
I have attached a sample event that is all-day recurring that is not pulled in my app. please let me know if this works, because it is not getting pulled by my code. 
[invite.zip](https://github.com/cloud-atlas-ai/obsidian-ics/files/14493123/invite.zip)

**Comment by The1029** [comment]
+1, I am experiencing the same issue. I've checked the days before/after but I'm not seeing anything. This appears to include both new events set to recur at later dates, and recurrences of previous events. If it helps, I am using NextCloud as my provider.

**Comment by The1029** [comment]
I can see that the version was recently bumped to 1.6.4 and this now appears to be reflecting in the community repo - I've just tested with a clean install from there and these are displaying correctly for me now.
