### ISSUE TITLE
Add ability to display ongoing multiday events

### ISSUE THREAD

**Issue by The1029** [cloud-atlas-ai/obsidian-ics#114]
Currently, the plugin only shows events that start on the specified date. If there are multiday events ongoing (start date *before* and end date *after* the daily note), these are not displayed on subsequent days. Is it possible/feasible to add this functionality? Whether it be as default, or optional behaviour.

**Comment by Cateroo** [comment]
+1

**Comment by The1029** [comment]
@Cateroo I have worked something out for this, but currently have a PR for a different issue and have made a mess of my forks/branches, so don't think I can have both ongoing at once! As soon as the ongoing PR is dealt with I'll raise a PR for this.
