### ISSUE TITLE
Checkbox won't stay disabled

### ISSUE THREAD

**Issue by novakwh** [cloud-atlas-ai/obsidian-ics#122]
Hi there, I love this plugin, it is perfect for my use case. But one thing I have noticed recently, when I disable the checkbox option for calendars (so that events show up as bullets only), it won't stay disabled -- every time I restart Obsidian, checkbox is enabled again for each calendar. (Other changes seem to save correctly; for example, if I make a change to the time format, then close and restart Obsidian, the change that I made is still there.)

EDIT: Ok, making this a little stranger, after I made the edit to the time format to see if that would save between sessions, the checkbox option started saving as disabled as well. BUT now it won't save if I re-enable it (it will remain toggled off when I restart Obsidian even if I had changed the toggle).

**Comment by muness** [comment]
Hmm, I haven't been able to reproduce the issue. I did notice that when the modal is up, if I just close the modal the settings affect the current session but don't get saved which is confusing and I should fix that.

@novakwh , can you confirm that you see the issue even when you save the settings using the ✔️ button on the calendar modal?

**Comment by muness** [comment]
@novakwh - I fixed the issues I saw in the settings dialog in [1.6.6](https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.6.6.1) 🤞 that fixes this problem for you, please let me know if it doesn't.

**Comment by muness** [comment]
> So if all you did was add the reminder to save, then I'm not sure why it seems to work now every time, but so far it is. Thanks again!

To be fair, I think there was an issue I fixed where I wasn't displaying the saved data correctly all the time. I've been using the Templater templates, so I'll admit that I have no idea how long those were messed up. I'll do better by doing some more testing of the formatting settings.

I am glad to hear it's fixed for you.
