### ISSUE TITLE
dataview only show today's schedule 

### ISSUE THREAD

**Issue by cllyreforce** [cloud-atlas-ai/obsidian-ics#127]
dataview only show today's schedule  ,i replace `getEvents(dv.current().file.day);
var mdArray = [];` with `getEvents(dv.page('Date'))`   that i have set Date in MetaData

```
var events = await app.plugins.getPlugin('ics').getEvents(dv.current().file.day);
var mdArray = [];
events.forEach((e) => {
  mdArray.push(`${e.time} ${e.summary} ${e.location}: ${e.description}`.trim())
})
dv.list(dv.array(mdArray))
```

**Comment by muness** [comment]
Hi @cllyreforce , sorry, just seeing this. I am not sure I follow the issue. Please clarify what you see / expect if this is still relevant and reopen the issue.
