### ISSUE TITLE
Vdir directory field doesn't work

### ISSUE THREAD

**Issue by novakwh** [cloud-atlas-ai/obsidian-ics#130]
Hi, the remote URL works great with this plugin, but when I select vdir, the directory field just shows a down arrow and I can't actually do anything with it. I'm assuming I should be able to select the directory for the vdirsyncer calendar in question, but I can't select anything.

**Comment by muness** [comment]
Hi @novakwh - that's for the bug report. There have been several updates to the Obsidian SDK and I may have been using a now unavailable way of retrieving folders. Will take a look later this week. 🤞

**Comment by muness** [comment]
Hi @novakwh - working for me, and I just got a PR #131 that added functionality to it, so I assume the person submitting it also has no issues. Can you reopen and talk me through what you're doing that doesn't work? Thanks!

**Comment by novakwh** [comment]
Hmm, nope -- this still doesn't work for me, perhaps I am doing something wrong. All plugins and Obsidian updated, using default theme, etc. I hit the + button next to Add new, and then in the Calendar Type dropdown I select vdir, and the calendar url text box field changes to a Directory dropdown field but there is nothing to select in the dropdown. See attached.
![Screenshot_20241130_155051](https://github.com/user-attachments/assets/2602de6a-7a68-4d39-b177-1c0af2f18ee7)

**Comment by muness** [comment]
The vdir has to be inside your vault. Is that where you have it?

**Comment by novakwh** [comment]
Ha, I thought it was, but apparently not -- that makes sense! Thanks.

**Comment by muness** [comment]
I'll see if I can improve the ui to indicate that no vdir directory was found.
