### ISSUE TITLE
Transparent Events are not showing up

### ISSUE THREAD

**Issue by Azurewren** [cloud-atlas-ai/obsidian-ics#140]
I get the following console messages when trying to import my Annual events:

`plugin:ics:23 Adding recurring event: Christmas Day Wed Dec 25 2024 08:00:00 GMT+0800 (Australian Western Standard Time) - Thu Dec 26 2024 00:00:00 GMT+0800 (Australian Western Standard Time)`
`plugin:ics:23 {type: 'VEVENT', params: Array(0), start: Wed Dec 25 2024 08:00:00 GMT+0800 (Australian Western Standard Time), datetype: 'date', end: Thu Dec 26 2024 00:00:00 GMT+0800 (Australian Western Standard Time), …}`
`plugin:ics:33 Excluding transparent event: Christmas Day`

The VEVENT Array does have a `transparency: "TRANSPARENT"` entry.

Can this be fixed, or perhaps can we be given an option where we can choose to allow transparent events to be shown? That is, if the Google Event Transparency is what the issue is of course.

**Comment by muness** [comment]
You want the transparent event? Apologies, that didn't even occur to me. Add it as a per calendar setting, do you think?

**Comment by Azurewren** [comment]
I do... I think though it should be an option because some people will only want to see events they are Busy for.. rather than Free events. :)

Yes, I think a Per Calendar setting would be perfect.

**Comment by muness** [comment]
Do you know why some events are TRANSPARENT?

**Comment by Azurewren** [comment]
From what I understand when you create an event (In Google Calendar) it is by default set as `Busy`, so it blocks out that timeslot. 

If you go into a Google calendar entry and scroll down to the entry just above the description field it should say `Busy` or `Free`. Events that are flagged as `Free` have their transparency set to Transparent. Busy events are Opaque. 

More info can be found at: https://developers.google.com/calendar/api/v3/reference/events#transparency or https://google-calendar-simple-api.readthedocs.io/en/latest/code/event.html#gcsa.event.Transparency

**Comment by muness** [comment]
Oh thank you! I must get very few of those Free events: I only noticed a transparent one last week which is why I implemented filtering them.
