### ISSUE TITLE
Add All Day Events

### ISSUE THREAD

**Issue by pib319** [cloud-atlas-ai/obsidian-ics#142]
Currently the Import Events command won't import any events that are "all day" and don't have an associated start or end time.

**Comment by muness** [comment]
I am not sure why I left these out or if there was a recent regression. Either way, a per calendar setting sound right to you, @pib319 ?

**Comment by pib319** [comment]
Sounds great! Appreciate your work :)

**Comment by muness** [comment]
Hmm, it's working on my end for multi-day events. (I do have to set Show Ongoing Events to true). Checking with a single all day event.

**Comment by muness** [comment]
Working on my end for single day all day events on Google Calendars at least.

**Comment by pib319** [comment]
Hmm, that's really odd because all day events arent working for me, I'm using Google calendar as well. Multi-day events work for me. 🤔

When ICS creates a task from your all day event, what does it list as the start time?

**Comment by muness** [comment]
Here's the single day event that I have that works for me:

```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20241229
DTEND;VALUE=DATE:20241230
DTSTAMP:20241230T020437Z
UID:6934ACB4-A950-43AD-A908-A566C226CEC9
CREATED:20241230T013924Z
LAST-MODIFIED:20241230T013924Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:TEST ALL DAY
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:P0DT9H0M0S
DESCRIPTION:This is an event reminder
END:VALARM
X-APPLE-CREATOR-IDENTITY:com.moleskine.timeline
X-APPLE-CREATOR-TEAM-IDENTITY:9M7AW744P4
END:VEVENT
```

On your end @pib319 , maybe you can download the ics file and look for the event that's not coming through and copy / paste / edit out personal info for me to look at? Thanks!

**Comment by muness** [comment]
> When ICS creates a task from your all day event, what does it list as the start time?

With format `MM-DD HH:mm` it shows as `- [ ] 12-29 00:00 - 12-30 00:00 Personal TEST ALL DAY`

**Comment by pib319** [comment]
@muness Here's how the event looks on my end. 
 
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20241229
DTEND;VALUE=DATE:20241230
DTSTAMP:20241230T024241Z
UID:2ro2atl2h6ukmf52fh7s15vg0u@google.com
CREATED:20241229T200712Z
LAST-MODIFIED:20241229T200712Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:test event
TRANSP:TRANSPARENT
END:VEVENT
```

I noticed the TRANSP property is set to "TRANSPENT". All of my events that have scheduled times have it set to OPAQUE. Could that be it?

**Comment by muness** [comment]
Yes, that could do it. I just added Transparent event support, also per calendar. See if toggling it on does the trick?

**Comment by pib319** [comment]
That worked! thank you so much :D
