### ISSUE TITLE
pass through more fields

### ISSUE THREAD

**Issue by pcause** [cloud-atlas-ai/obsidian-ics#90]
For those of us scripting the format, could you pass through additional fields.  I've like the free/busy (I can use css to color differently in my script).    Think you should also add an element to the IEvent structure to say if a vevent or vtodo and allow an option for also handling vtodos which you now skip even though the data structure for ics parser handles both  .  this allows scripters to handle external todos from ics sources.  I wouldn't pass the vtodos through to the simple interface just for scripters.

**Comment by muness** [comment]
Ah, thanks for raising this @pcause . I see these fields:
- busy/free (I'll have to dig for that in the vevent spec)
- todo vs. event (sounds like that's the type, being vtodo or vevent)

Anything else?

**Comment by muness** [comment]
@pcause - what calendar provider are you using that supports vtodo? I tried Google Calendar and as far as I can tell, they don't include tasks as vtodo entries.

**Comment by pcause** [comment]
I am not sure I am using yet, but on MS365 and hoping MS Todo might.

**Comment by muness** [comment]
From searching the interwebs, I saw that Outlook doesn't support VTODO so I doubt it. Let me know if you find a server/client and I'd be happy to figure out support (as I'd love to use it too!)
