### ISSUE TITLE
Broken link for advanced example

### ISSUE THREAD

**Issue by chmac** [cloud-atlas-ai/obsidian-ics#95]
When I click the advanced template example link on the readme I get a GitHub 404 page.

**Comment by muness** [comment]
Thanks for the report. I moved the repo last week and forgot to update the links. Will fix later today.

**Comment by muness** [comment]
@chmac : Updated the README. https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74 for your convenience.

**Comment by chmac** [comment]
@muness Awesome, thanks for the super fast response!
