### ISSUE TITLE
recurrent events now break plugin completely. What has changed?

### ISSUE THREAD

**Issue by seatrout** [cloud-atlas-ai/obsidian-ics#96]
For the last five days, the plugin has been horrible broken: it finds huge numbers of recurrent events from past years ands spews them into my daily note, complaining about "Invalid date" — this with a template that was working perfectly well before Christmas.

Using this template fragment (adjusted to fit the way I name my diaries):

```
<%*  
var events = await app.plugins.getPlugin('ics').getEvents(moment(tp.file.title,'DD MMMM YYYY - dddd'));  
if (events.length) {  
    tR+= `>[!Danger]- Today's Schedule\n`  
    events.sort((a,b) => a.utime - b.utime).forEach((e) => {  
        const calendar = e.icsName.replace(" ","-");  
        const callUrl = e.callUrl? ` [${e.callType}](${e.callUrl})` : '';  
        const location = e.location? ` 📍 *(${e.location})*` : '';  
        tR+=`- [ ] ${e.time}-${e.endTime} **${e.summary}**${location}${callUrl} #${calendar}\n`  
        if (e.description) {  
            const inlineDescription = e.description.replace(/(?:\r\n|\r|\n)/g," ").replace(/\s{2,}/g," ");  
            tR+=`    - ${inlineDescription}\n`  
        }  
    })  
}  
%>  


```

I get hundreds of lines complaining of "Invalid date" in recurring events that have long since passed, and don't in any case affect today:

like this: 

```
# testing ICS
- [ ] Invalid date-Invalid date **Mary Heley** 📍 *(XXXXXX)* #seatrout
  {Repeat 17 times}

- [ ] Invalid date-Invalid date **Renew prescription** #seatrout
- [ ] {repeat 164 times}

- [ ] Invalid date-Invalid date **RMC editorial meeting** 📍 *(zoom see below)* #seatrout
 { repeat 12 times} 
 
 ... and so on, some of these errors going back *20 years*

 ```

I have tried this with a conventionally named date template too: it is clearly something in the handling of recurrent events in the plugin.

**Comment by seatrout** [comment]
Looking at the console, there are 983 messages from the plugin (no errors) — of which this is a typical fragment : 

```
Cloned event: Object
plugin:ics:22 Found a recurring event to clone:  Ann the cleaner  on  Invalid Date at  Wed Jan 12 2022 11:30:00 GMT+0000 (Greenwich Mean Time)
plugin:ics:22 RRULE origOptions: Object
plugin:ics:22 Event rrule.origOptions.tzid: Europe/London
plugin:ics:22 Cloned event: Object
plugin:ics:22 Found a recurring event to clone:  Ann the cleaner  on  Invalid Date at  Wed Jan 12 2022 11:30:00 GMT+0000 (Greenwich Mean Time)
plugin:ics:22 RRULE origOptions: Object
plugin:ics:22 Event rrule.origOptions.tzid: Europe/London
plugin:ics:22 Cloned event: 
```

**Comment by muness** [comment]
Thanks for the report. When I moved the repo I updated the `node-ical` package. That likely broke the recurring rule parsing.

My apologies. You can try the previous release of you'd like while I revert the dependency upgrade in the next few hours.

**Comment by muness** [comment]
- Likely culprit: https://github.com/cloud-atlas-ai/obsidian-ics/commit/1469250ff8f679eba268f39aedd490eb6f95eb27
- Which leads to https://github.com/jens-maus/node-ical/issues/291

Reverting back to 0.16.1

**Comment by muness** [comment]
@seatrout - what calendar providers are you using? I'm trying to reproduce the issue and I don't see the issue with Google Calendar feeds.

**Comment by muness** [comment]
I tried 0365 calendars too without being able to reproduce.

From looking at the provided screenshot I see `APPLE-TRAVEL-ADVISORY-BEHAVIOR` which I believe is an Apple specific calendar entry, will see if I can create an iCloud hosted calendar.

**Comment by seatrout** [comment]
I'm using Google. I don't know where the Apple thing came from, except that one of these Google calendars is shared with my wife, who does keep an Apple calendar.

**Comment by seatrout** [comment]
The "RMC Editorial meetings" may also be shared with people who use Apple providers. But most of the calendars referenced in the file are Google, even if they are shared.

**Comment by seatrout** [comment]
Do shared calendars put out a different ICS feed/ That seems very unlikely to me, but what would I know?

**Comment by muness** [comment]
You are correct, they should not be any different.

@seatrout - can you try the release before the update? https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.5.0 . Replace `main.js` in your `<vault>/.obsidian/plugins/ics` with the one at that release and then import the day's events again. Thanks!

**Comment by muness** [comment]
> @seatrout - can you try the release before the update? https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.5.0 . Replace `main.js` in your `<vault>/.obsidian/plugins/ics` with the one at that release and then import the day's events again. Thanks!

Oh, and you'll need to restart Obsidian before trying to re-import

**Comment by seatrout** [comment]
Yay! That works again. Thank you — what exactly changed to break things? 
Anyway, thank you so much for fixing this so quickly.

**Comment by muness** [comment]
> Yay! That works again. Thank you — what exactly changed to break things? Anyway, thank you so much for fixing this so quickly.

I haven't changed anything yet. ;) 

1.5.0 works for you?

**Comment by seatrout** [comment]
Just to confirm: 1.50 works again, yes. 
(That Obsidian is taking _minutes_ to reload — presumably to rebuild — its cache files when restarted is not your problem)

**Comment by seatrout** [comment]
So it was the update in `node-ical`  which broke this?

**Comment by muness** [comment]
> So it was the update in `node-ical` which broke this?

I believe so, which in turn pulled in changes to `rrule`.

I'd rather not revert to 0.16.1 as it's showing a dependency on a vulnerable `axios`:
```
node_modules/axios
  node-ical  0.14.0 - 0.16.1
  Depends on vulnerable versions of axios
  node_modules/node-ical
```
I am exploring other options now, would love help testing once I get an idea...

**Comment by muness** [comment]
k, looks like I can lock `rrule` to a previous version even while updating `node-ical`... Testing that locally.

**Comment by seatrout** [comment]
Happy to help test this
But when I look at these complications and dependencies I am so glad I am not a developer.

**Comment by muness** [comment]
@seatrout , https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.5.1-lockrrule3 works for me locally (but I never suffered the breakage). In this release I keep the update to `node-ical` but lock `rrule` to `2.6.6`.

Hoping this no longer shows the erroneous recurring events for you when you try it. You'll replace the `main.js` again, restart and then try again.

Thanks!

**Comment by muness** [comment]
One more https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.5.1-lockrrule4 - this uses the last `rrule` 2.6.8 release on the 2.6 version.

**Comment by muness** [comment]
> But when I look at these complications and dependencies I am so glad I am not a developer.

It's all part of the cost of being able to make computers do all the things they do. ;)

**Comment by muness** [comment]
Actually, I realized that the above build still had the older `axios` dependency. 

@seatrout : Please let me know if the latest, https://github.com/cloud-atlas-ai/obsidian-ics/releases/tag/1.5.3 release maintains the fix and we can close this. If you're still seeing it, I am sure we can find some other solution...

**Comment by seatrout** [comment]
Is it only main.js that's changed and needs replacing?

**Comment by muness** [comment]
Yes. if you want the version number to show up correctly that's in `manifest.json`

**Comment by seatrout** [comment]
The 1.5.3 version works, both when there is an event that day, whether it recurs or not, and when there are none. Thank you so much.

**Comment by muness** [comment]
Thanks for the report and helping test. I wish I could reproduce the issue so I can test against whatever is going wrong in future releases. 

For now I'll count on you and other users to let me know if the issue comes back. ;)

**Comment by seatrout** [comment]
Everything still works, and I am still grateful :-) 
But in the night I thought of a reason that you might not have been able to reproduce this bug: all of the problems I can remember were _expired_ sequences of recurring events. Recurring events which are still recurring today didn't, so far as I can remember, trigger the bug. But eg "Ann the cleaner" (from my example upthread) no longer comes to clean, so all her end dates showed up as invalid. I think that's it, anyway.

**Comment by muness** [comment]
> Everything still works, and I am still grateful :-)

😌 , phew, I was worried the issue came back the next day when I saw the email notification!

> a reason that you might not have been able to reproduce this bug: all of the problems I can remember were _expired_ sequences of recurring events.

Thanks @seatrout , I'll see if that helps in reporducing the issue.
