### ISSUE TITLE
Is it possible to get the event guests too?

### ISSUE THREAD

**Issue by andrecarlucci** [cloud-atlas-ai/obsidian-ics#99]
Hi, thanks for this amazing plugin.
Is it possible to show the guest list with their responses (accepted or not) under every event?
Tks!

**Comment by muness** [comment]
I've poked at this before and it should be doable, yes. I'd punted on it because it was part of #19 which went further but this would be a relatively easy step towards that.

**Comment by andrecarlucci** [comment]
Thank you!

**Comment by muness** [comment]
Shameless plug: Am using another plugin, https://github.com/cloud-atlas-ai/obsidian-client to build this! 

![image](https://github.com/cloud-atlas-ai/obsidian-ics/assets/931/9a8e6dba-ed3d-4e27-80fb-98cfbd4feafd)

😀

**Comment by muness** [comment]
@andrecarlucci - ideas in terms of the participant list formatting?

**Comment by andrecarlucci** [comment]
@muness I'm new to obsidian, but this is the thing I would like to have:

Every day, I open my daily note and get the list of meetings. This part works really well (thanks!) and I formatted the list to use proper Headings so I can reference that section elsewhere.

I have one note that represents a Person. All sorts of information there.

In every meeting, I interact with other people. From the meeting guests, I would like to create a subheading for each person, linking it with their Personal Note (a note I create for each Person I interact with). Now, there is the challenge of mapping names and emails with the names I use for the personal notes, but that's another thing.

For the feature, wouldn't be better to just have those "models" as a Json structure where Plugin users could template the output the way they want? You document the json structure with the plugin and everything else becomes configuration.

Wdyt?

**Comment by muness** [comment]
> For the feature, wouldn't be better to just have those "models" as a Json structure where Plugin users could template the output the way they want? You document the json structure with the plugin and everything else becomes configuration.

That's exactly how it works. The built-in uses the same object as the [community supplied templates](https://github.com/cloud-atlas-ai/obsidian-ics/discussions/74) and is documented in the [IEvent](https://github.com/cloud-atlas-ai/obsidian-ics/blob/master/src/IEvent.ts) interface.

In the PR implementing the participant list, I added a guest interface and an array of guests to an event: https://github.com/cloud-atlas-ai/obsidian-ics/blob/dad4fc23047faa095bf486ad13f2c7173188ac47/src/IEvent.ts 

@andrecarlucci : Any suggestions for the json structure?

**Comment by andrecarlucci** [comment]
Nice! I will experiment with it. Thank you!
